/*
 * JS for uploadPage generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'c8549c18-155f-4a63-9a8b-6d935032b35c';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "viewingPage",
    "location": "viewingPage.html"
}, {
    "name": "loginPage",
    "location": "loginPage.html"
}, {
    "name": "uploadPage",
    "location": "uploadPage.html"
}];

function uploadPage_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_5': 'uploadPage_mobilebutton_5',
        'html_86': 'uploadPage_html_86',
        'mobilegrid_17': 'uploadPage_mobilegrid_17',
        'mobilegridcell_18': 'uploadPage_mobilegridcell_18',
        'mobilegridcell_19': 'uploadPage_mobilegridcell_19',
        'mobileimage_24': 'uploadPage_mobileimage_24',
        'mobilegridcell_22': 'uploadPage_mobilegridcell_22',
        'mobilelabel_7': 'uploadPage_mobilelabel_7',
        'photoInput': 'uploadPage_photoInput',
        'mobilelabel_16': 'uploadPage_mobilelabel_16',
        'tagInput': 'uploadPage_tagInput',
        'mobilelabel_6': 'uploadPage_mobilelabel_6',
        'uploadButton': 'uploadPage_uploadButton',
        'uploadInProgressLabel': 'uploadPage_uploadInProgressLabel',
        'mobilegrid_29': 'uploadPage_mobilegrid_29',
        'mobilegridcell_30': 'uploadPage_mobilegridcell_30',
        'mobilegridcell_31': 'uploadPage_mobilegridcell_31',
        'html_36': 'uploadPage_html_36',
        'mobilegridcell_34': 'uploadPage_mobilegridcell_34',
        'mobilegrid_8': 'uploadPage_mobilegrid_8',
        'mobilegridcell_9': 'uploadPage_mobilegridcell_9',
        'mobilegridcell_10': 'uploadPage_mobilegridcell_10',
        'mobileimage_15': 'uploadPage_mobileimage_15',
        'mobilegridcell_13': 'uploadPage_mobilegridcell_13',
        'html_85': 'uploadPage_html_85',
        'mobilelabel_26': 'uploadPage_mobilelabel_26',
        'mobilelabel_28': 'uploadPage_mobilelabel_28',
        'mobilebutton_27': 'uploadPage_mobilebutton_27',
        'mobilegrid_66': 'uploadPage_mobilegrid_66',
        'mobilegridcell_67': 'uploadPage_mobilegridcell_67',
        'mobilelabel_65': 'uploadPage_mobilelabel_65',
        'mobilegrid_71': 'uploadPage_mobilegrid_71',
        'mobilegridcell_72': 'uploadPage_mobilegridcell_72',
        'mobilelabel_38': 'uploadPage_mobilelabel_38',
        'mobilegrid_40': 'uploadPage_mobilegrid_40',
        'mobilegridcell_41': 'uploadPage_mobilegridcell_41',
        'mobilegridcell_42': 'uploadPage_mobilegridcell_42',
        'mobileimage_39': 'uploadPage_mobileimage_39',
        'mobilegridcell_45': 'uploadPage_mobilegridcell_45',
        'mobilegrid_78': 'uploadPage_mobilegrid_78',
        'mobilegridcell_79': 'uploadPage_mobilegridcell_79',
        'mobilelabel_47': 'uploadPage_mobilelabel_47',
        'mobilegrid_48': 'uploadPage_mobilegrid_48',
        'mobilegridcell_49': 'uploadPage_mobilegridcell_49',
        'mobilegridcell_50': 'uploadPage_mobilegridcell_50',
        'mobileimage_54': 'uploadPage_mobileimage_54',
        'mobilegridcell_53': 'uploadPage_mobilegridcell_53',
        'mobilegrid_83': 'uploadPage_mobilegrid_83',
        'mobilegridcell_84': 'uploadPage_mobilegridcell_84',
        'mobilelabel_55': 'uploadPage_mobilelabel_55',
        'mobilegrid_57': 'uploadPage_mobilegrid_57',
        'mobilegridcell_58': 'uploadPage_mobilegridcell_58',
        'mobilegridcell_59': 'uploadPage_mobilegridcell_59',
        'mobileimage_64': 'uploadPage_mobileimage_64',
        'mobilegridcell_62': 'uploadPage_mobilegridcell_62',
        'mobilebutton_56': 'uploadPage_mobilebutton_56'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["uploadPage_picUpload_service_onsuccess_mapping_0"] = {
        "homeScreen": "uploadPage",
        "directions": []
    };

    Apperyio.mappings["uploadPage_picUpload_service_onbeforesend_mapping_0"] = {
        "homeScreen": "uploadPage",
        "directions": [

        {
            "from_name": "sessionToken",
            "from_type": "LOCAL_STORAGE",

            "to_name": "picUpload_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['headers']['X-Appery-Session-Token']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["uploadPage_uploadPage_login_service_onsuccess_mapping_0"] = {
        "homeScreen": "uploadPage",
        "directions": [

        {
            "from_name": "uploadPage_login_service",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "sessionToken",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['body']['sessionToken']",
                "target": "$"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["uploadPage_uploadPage_login_service_onbeforesend_mapping_0"] = {
        "homeScreen": "uploadPage",
        "directions": [

        {

            "to_name": "uploadPage_login_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "target_transformation": function(value) {
                    return "anyUser";
                },
                "target": "$['body']['username']"

            },

            {

                "target_transformation": function(value) {
                    return "anyUser";
                },
                "target": "$['body']['password']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["uploadPage_picInfo_create_service_onsuccess_mapping_0"] = {
        "homeScreen": "uploadPage",
        "directions": []
    };

    Apperyio.mappings["uploadPage_picInfo_create_service_onbeforesend_mapping_0"] = {
        "homeScreen": "uploadPage",
        "directions": [

        {
            "from_name": "photoFilename",
            "from_type": "LOCAL_STORAGE",

            "to_name": "picInfo_create_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": {
                    "acl": {
                        "*": {
                            "write": true,
                            "read": true
                        }
                    }
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['photoName']"

            }

            ]
        },

        {
            "from_name": "uploadPage",
            "from_type": "UI",

            "to_name": "picInfo_create_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": {
                    "acl": {
                        "*": {
                            "write": true,
                            "read": true
                        }
                    }
                }
            },

            "mappings": [

            {

                "source": "$['tagInput:text']",
                "target": "$['body']['peopleTags']"

            }

            ]
        },

        {

            "to_name": "picInfo_create_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": {
                    "acl": {
                        "*": {
                            "write": true,
                            "read": true
                        }
                    }
                }
            },

            "mappings": [

            {

                "target_transformation": function(value) {
                    // var deviceOS = localStorage.getItem('deviceOS');
                    var exifCode;

                    // if ( deviceOS == 'iOS' ) {
                    exifCode = localStorage.getItem('exifCode');
/* } else {
    exifCode = 'none';
} */

                    return exifCode;
                },
                "target": "$['body']['exifCode']"

            },

            {

                "target_transformation": function(value) {
                    return localStorage.getItem("uploadImgNaturalWidth");

                },
                "target": "$['body']['naturalW']"

            },

            {

                "target_transformation": function(value) {

                    // no encoded thumbnail any longer
                    // return localStorage.getItem("thumbnail_id");
                    return 'N/A';
                },
                "target": "$['body']['thumbnail_id']"

            },

            {

                "target_transformation": function(value) {
                    var v = localStorage.getItem('deviceOS');
                    var r;

                    if (v == "android") {

                        r = "A";

                    } else {

                        r = "I";

                    }

                    return r;
                },
                "target": "$['body']['photoDeviceOS']"

            },

            {

                "target_transformation": function(value) {
                    var todayDate = new Date();
                    var yyyy = todayDate.getFullYear();
                    var mm = todayDate.getMonth() + 1;
                    var dd = todayDate.getDate();
                    // console.log("getDate() =" + dd);
                    if (mm < 10) {
                        mm = "0" + mm;
                    }

                    if (dd < 10) {
                        dd = "0" + dd;
                    }

                    var hr = todayDate.getHours();

                    if (hr < 10) {
                        hr = "0" + hr;
                    }

                    var min = todayDate.getMinutes();

                    if (min < 10) {
                        min = "0" + min;
                    }

                    var str = yyyy + '/' + mm + '/' + dd + ' - ' + hr + ':' + min;

                    return str;
                },
                "target": "$['body']['dateTime']"

            },

            {

                "target_transformation": function(value) {
                    return "0";
                },
                "target": "$['body']['likes']"

            },

            {

                "target_transformation": function(value) {

                    return localStorage.getItem("uploadImgNaturalHeight");
                },
                "target": "$['body']['naturalH']"

            },

            {

                "target_transformation": function(value) {
                    var v1 = localStorage.getItem("hcjName");
                    var v2 = localStorage.getItem("hcjFirstname");

                    return v2 + ' ' + v1;

                },
                "target": "$['body']['owner']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["uploadPage_thumbnail_create_service_onsuccess_mapping_0"] = {
        "homeScreen": "uploadPage",
        "directions": []
    };

    Apperyio.mappings["uploadPage_thumbnail_create_service_onbeforesend_mapping_0"] = {
        "homeScreen": "uploadPage",
        "directions": [

        {
            "from_name": "photoFilename",
            "from_type": "LOCAL_STORAGE",

            "to_name": "thumbnail_create_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": {
                    "acl": {
                        "*": {
                            "write": true,
                            "read": true
                        }
                    }
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['photoName']"

            }

            ]
        },

        {

            "to_name": "thumbnail_create_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": {
                    "acl": {
                        "*": {
                            "write": true,
                            "read": true
                        }
                    }
                }
            },

            "mappings": [

            {

                "target_transformation": function(value) {

                    //var deviceOS = localStorage.getItem('deviceOS');
                    var exifCode;

                    //if ( deviceOS == 'iOS' ) {
                    exifCode = localStorage.getItem('exifCode');
/*} else {
    exifCode = 'none';
}*/

                    return exifCode;
                },
                "target": "$['body']['exifCode']"

            },

            {

                "target_transformation": function(value) {
                    var b64str = localStorage.getItem('thumbnailPic2upload');

                    return b64str;

                },
                "target": "$['body']['photoThumbnail']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["uploadPage_uploadPage_VersionCheck2reload_service_onsuccess_mapping_0"] = {
        "homeScreen": "uploadPage",
        "directions": []
    };

    Apperyio.mappings["uploadPage_uploadPage_VersionCheck2reload_service_onbeforesend_mapping_0"] = {
        "homeScreen": "uploadPage",
        "directions": [

        {

            "to_name": "uploadPage_VersionCheck2reload_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "Content-Type": "text/plain"
                },
                "parameters": {},
                "body": null
            },

            "mappings": []
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.picUpload_service = Apperyio.datasources.picUpload_service = new Apperyio.DataSource(HCJquizDB__files_upload_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["uploadPage_picUpload_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["uploadPage_picUpload_service_onsuccess_mapping_0"]);
            // [{"success":{"filename":"b28de18f-da05-4e8b-9382-f5227dc2fc46.static_qr_code_without_logo.jpg","fileurl":"https://api.appery.io/rest/1/db/files/5930beb22e22d76ace4c378d/b28de18f-da05-4e8b-9382-f5227dc2fc46.static_qr_code_without_logo.jpg"}}]
            var v = data[0].success.filename;
            // console.log('filename = '+v);
            localStorage.setItem('photoFilename', v);

            // no encoded thumbnail HOWEVER still loading the img in the browser is needed to get natural width and height
            $("#uploadPage_uploadInProgressLabel").text("obtaining the picture's information ... pls wait.");
            thumbnailB64data();

            ;
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            $("#uploadPage_uploadInProgressLabel").slideUp();
            $("#uploadPage_uploadButton").attr("disabled", false);

            alert("Oops! something went wrong while uploading to the server. Please try again.");
        }
    });

    window.uploadPage_login_service = Apperyio.datasources.uploadPage_login_service = new Apperyio.DataSource(HCJquizDB_login_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["uploadPage_uploadPage_login_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["uploadPage_uploadPage_login_service_onsuccess_mapping_0"]);

            $("#uploadPage_uploadInProgressLabel").slideDown();

            // $("#uploadPage_progressBarHTML").show();
            // localStorage.setItem('progressBarGate',1);
            // progressBar(1);
            // trigger Appery API to upload the file to the _files table
            uploadMultipleFilesHelper(picUpload_service, Apperyio('photoInput'));
            // then onSuccess will retrieve file name to store in LS

            ;
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            $("#uploadPage_uploadInProgressLabel").slideUp();
            $("#uploadPage_uploadButton").attr("disabled", false);

            alert("Oops! something went wrong while connecting to the server. Please try again.");
        }
    });

    window.picInfo_create_service = Apperyio.datasources.picInfo_create_service = new Apperyio.DataSource(HCJquizDB_photoInfos_create_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["uploadPage_picInfo_create_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
            $("#uploadPage_uploadButton").attr("disabled", false);;

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["uploadPage_picInfo_create_service_onsuccess_mapping_0"]);

            $("#uploadPage_uploadInProgressLabel").slideUp();
            // $("#uploadPage_progressBarHTML").hide();
            // localStorage.setItem('progressBarGate',0);

            // $("#uploadPage_uploadSuccessTweetPopup").popup("open");
            setTimeout(function() {
                $("#uploadPage_photoInput").val("");
                $("#uploadPage_tagInput").val("");
                $("#uploadPage_uploadInProgressLabel").text("upload in progress ... pls wait.");
                alert('Your picture was successfully uploaded.');
            }, 800);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            $("#uploadPage_uploadInProgressLabel").slideUp();
            // $("#uploadPage_progressBarHTML").hide();
            // localStorage.setItem('progressBarGate',0);
            $("#uploadPage_uploadButton").attr("disabled", false);

            alert("Oops! something went wrong. Please try again.");
        }
    });

    window.thumbnail_create_service = Apperyio.datasources.thumbnail_create_service = new Apperyio.DataSource(HCJquizDB_thumbnails_create_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["uploadPage_thumbnail_create_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["uploadPage_thumbnail_create_service_onsuccess_mapping_0"]);
            // console.log('data= '+JSON.stringify(data));
            // data= {"_id":"5944c60e6b0182322f93c22b","_createdAt":"2017-06-17 06:02:54.318"}
            // localStorage.setItem("thumbnail_id",data._id);
            $("#uploadPage_uploadInProgressLabel").text("recording the picture's information.");
            try {
                picInfo_create_service.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.uploadPage_VersionCheck2reload_service = Apperyio.datasources.uploadPage_VersionCheck2reload_service = new Apperyio.DataSource(hcjUpdateReloadCheck_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["uploadPage_uploadPage_VersionCheck2reload_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["uploadPage_uploadPage_VersionCheck2reload_service_onsuccess_mapping_0"]);
            console.log('data = ' + data.newVersion)

            var v = localStorage.getItem('uploadPageVersionNum');

            if (v != data.newVersion) {

                alert("A new update was pushed, your page will reload. Please wait.");
                localStorage.setItem('uploadPageVersionNum', data.newVersion);

                location.reload();

            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'uploadPage';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var uploadPage_onLoad = function() {
            uploadPage_elementsExtraJS();

            // pastBetaVersionMark('uploadPage');
            $("#uploadPage_uploadInProgressLabel").hide();
            $("#uploadPage_progressBarHTML").hide();;

            uploadPage_deviceEvents();
            uploadPage_windowEvents();
            uploadPage_elementsEvents();
        };

    // screen window events


    function uploadPage_windowEvents() {

        $('#uploadPage').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
        $('#uploadPage').on({
            pageshow: function(event) { // exifCode:
                // var deviceOS = localStorage.getItem('deviceOS');
                // if ( deviceOS == 'iOS' ) {
                var input = document.getElementById('uploadPage_photoInput');
                input.onchange = function(e) {
                    getOrientation(input.files[0], function(orientation) {
                        localStorage.setItem('exifCode', orientation);
                        // alert('orientation: ' + orientation);
                    });
                }
/*} else { // android => not available
    'N/A';
}*/

                // set 1st time loadingPage load to 1
                var check = localStorage.getItem('loadingPage1stTimeLoad');
                if (check == "1") {
                    $("#uploadPage_uploadPageTutoPopup").popup("open");
                    localStorage.setItem('loadingPage1stTimeLoad', 0);

                };
                try {
                    uploadPage_VersionCheck2reload_service.execute({});
                } catch (e) {
                    console.error(e);
                    hideSpinner();
                };
            },
        });

    };

    // device events


    function uploadPage_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function uploadPage_elementsExtraJS() {
        // screen (uploadPage) extra code

        /* uploadSuccessTweetPopup */
        $("#uploadPage_uploadSuccessTweetPopup").popup("option", "positionTo", "#uploadPage_photoInput");

        /* uploadPageTutoPopup */
        $("#uploadPage_uploadPageTutoPopup").popup("option", "positionTo", "#uploadPage_mobileheader");

    };

    // screen elements handler


    function uploadPage_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#uploadPage_mobileheader [name="mobilebutton_5"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('viewingPage', {
                        reverse: false
                    });

                }
            },
        }, '#uploadPage_mobileheader [name="mobilebutton_5"]');

        $(document).off("click", '#uploadPage_mobilecontainer [name="uploadButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    var v2 = $("#uploadPage_photoInput").val();

                    if (v2 == "") { // no photo in file input
                        alert("Please select the photo to be uploaded.")

                    } else { // photo selected
                        var v = $("#uploadPage_tagInput").val();

                        if (v == "") {

                            var r = confirm("Don't you key in any tag for this picture? no tag [OK] / tag [cancel]");

                            if (r === true) {
                                uploadPage_login_service.execute({});
                                $("#uploadPage_uploadButton").attr("disabled", "disabled");
                            }

                        } else {

                            uploadPage_login_service.execute({});
                            $("#uploadPage_uploadButton").attr("disabled", "disabled");

                        }

                    };

                }
            },
        }, '#uploadPage_mobilecontainer [name="uploadButton"]');

        $(document).off("click", '#uploadPage_uploadSuccessTweetPopup [name="mobilebutton_27"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) { // $("#uploadPage_uploadSuccessTweetPopup").popup("close");
                    ;

                }
            },
        }, '#uploadPage_uploadSuccessTweetPopup [name="mobilebutton_27"]');

        $(document).off("click", '#uploadPage_uploadPageTutoPopup [name="mobilebutton_56"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio('uploadPageTutoPopup').popup('close');

                }
            },
        }, '#uploadPage_uploadPageTutoPopup [name="mobilebutton_56"]');

    };

    $(document).off("pagebeforeshow", "#uploadPage").on("pagebeforeshow", "#uploadPage", function(event, ui) {
        Apperyio.CurrentScreen = "uploadPage";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    uploadPage_onLoad();
};

$(document).off("pagecreate", "#uploadPage").on("pagecreate", "#uploadPage", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    uploadPage_js();
});