/*
 * JS for viewingPage generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '978a88be-e229-4d16-9f0c-afd594072543';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "uploadPage",
    "location": "uploadPage.html"
}, {
    "name": "loginPage",
    "location": "loginPage.html"
}, {
    "name": "viewingPage",
    "location": "viewingPage.html"
}];

function viewingPage_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_11': 'viewingPage_mobilebutton_11',
        'mobilebutton_18': 'viewingPage_mobilebutton_18',
        'html_61': 'viewingPage_html_61',
        'html_12': 'viewingPage_html_12',
        'mobilegrid_34': 'viewingPage_mobilegrid_34',
        'mobilegridcell_35': 'viewingPage_mobilegridcell_35',
        'mobilelabel_22': 'viewingPage_mobilelabel_22',
        'ownerParamInput': 'viewingPage_ownerParamInput',
        'tagParamInput': 'viewingPage_tagParamInput',
        'mobilebutton_17': 'viewingPage_mobilebutton_17',
        'mobilegrid_49': 'viewingPage_mobilegrid_49',
        'mobilegridcell_50': 'viewingPage_mobilegridcell_50',
        'mobilelabel_33': 'viewingPage_mobilelabel_33',
        'mobilebutton_20': 'viewingPage_mobilebutton_20',
        'mobilegrid_44': 'viewingPage_mobilegrid_44',
        'mobilegridcell_45': 'viewingPage_mobilegridcell_45',
        'mobilelabel_52': 'viewingPage_mobilelabel_52',
        'mobilelabel_32': 'viewingPage_mobilelabel_32',
        'mobilegrid_24': 'viewingPage_mobilegrid_24',
        'mobilegridcell_25': 'viewingPage_mobilegridcell_25',
        'mobilegridcell_26': 'viewingPage_mobilegridcell_26',
        'mobileimage_31': 'viewingPage_mobileimage_31',
        'mobilegridcell_29': 'viewingPage_mobilegridcell_29',
        'mobilegrid_53': 'viewingPage_mobilegrid_53',
        'mobilegridcell_54': 'viewingPage_mobilegridcell_54',
        'mobilebutton_21': 'viewingPage_mobilebutton_21',
        'mobilegridcell_55': 'viewingPage_mobilegridcell_55',
        'mobilebutton_51': 'viewingPage_mobilebutton_51',
        'mosaicViewerImg': 'viewingPage_mosaicViewerImg',
        'mobilebutton_60': 'viewingPage_mobilebutton_60'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["viewingPage_viewer_photoQuery_service_onsuccess_mapping_0"] = {
        "homeScreen": "viewingPage",
        "directions": []
    };

    Apperyio.mappings["viewingPage_viewer_photoQuery_service_onbeforesend_mapping_0"] = {
        "homeScreen": "viewingPage",
        "directions": [

        {
            "from_name": "viewingPage",
            "from_type": "UI",

            "to_name": "viewer_photoQuery_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "Content-Type": "text/plain"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$['tagParamInput:text']",
                "target": "$['parameters']['tag']"

            },

            {

                "source": "$['ownerParamInput:text']",
                "target": "$['parameters']['owner']"

            }

            ]
        },

        {

            "to_name": "viewer_photoQuery_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "Content-Type": "text/plain"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "target_transformation": function(value) {
                    var deviceOS = localStorage.getItem('deviceOS');
                    return deviceOS;
                },
                "target": "$['parameters']['deviceOS']"

            },

            {

                "target_transformation": function(value) {
                    var v1 = localStorage.getItem('hcjName'),
                        v2 = localStorage.getItem('hcjFirstname');

                    return v2 + ' ' + v1;
                },
                "target": "$['parameters']['user']"

            },

            {

                "target_transformation": function(value) {
                    var inH = window.innerHeight;

                    return inH;
                },
                "target": "$['parameters']['winH']"

            },

            {

                "target_transformation": function(value) {
                    var inW = window.innerWidth;

                    return inW;
                },
                "target": "$['parameters']['winW']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["viewingPage_viewer_photoLike_service_onsuccess_mapping_0"] = {
        "homeScreen": "viewingPage",
        "directions": []
    };

    Apperyio.mappings["viewingPage_viewer_photoLike_service_onbeforesend_mapping_0"] = {
        "homeScreen": "viewingPage",
        "directions": [

        {
            "from_name": "likePhoto_photoName",
            "from_type": "LOCAL_STORAGE",

            "to_name": "viewer_photoLike_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "Content-Type": "text/plain"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target_transformation": function(value) {
                    if (value) {
                        console.log('value = ' + value);
                    }
                },
                "target": "$['parameters']['photoName']"

            }

            ]
        },

        {
            "from_name": "likePhoto_folkName",
            "from_type": "LOCAL_STORAGE",

            "to_name": "viewer_photoLike_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "Content-Type": "text/plain"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target_transformation": function(value) {
                    if (value) {
                        console.log('value = ' + value);
                    }
                },
                "target": "$['parameters']['likingFolk']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["viewingPage_viewer_top10Likes_service_onsuccess_mapping_0"] = {
        "homeScreen": "viewingPage",
        "directions": []
    };

    Apperyio.mappings["viewingPage_viewer_top10Likes_service_onbeforesend_mapping_0"] = {
        "homeScreen": "viewingPage",
        "directions": [

        {

            "to_name": "viewer_top10Likes_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "Content-Type": "text/plain"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "target_transformation": function(value) {
                    var v1 = localStorage.getItem('hcjName'),
                        v2 = localStorage.getItem('hcjFirstname');

                    return v2 + ' ' + v1;
                },
                "target": "$['parameters']['user']"

            },

            {

                "target_transformation": function(value) {
                    var deviceOS = localStorage.getItem('deviceOS');
                    return deviceOS;
                },
                "target": "$['parameters']['deviceOS']"

            },

            {

                "target_transformation": function(value) {
                    var inW = window.innerWidth;

                    return inW;
                },
                "target": "$['parameters']['winW']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["viewingPage_viewer_selectPhoto_create_service_onsuccess_mapping_0"] = {
        "homeScreen": "viewingPage",
        "directions": []
    };

    Apperyio.mappings["viewingPage_viewer_selectPhoto_create_service_onbeforesend_mapping_0"] = {
        "homeScreen": "viewingPage",
        "directions": [

        {

            "to_name": "viewer_selectPhoto_create_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": {
                    "acl": {
                        "*": {
                            "write": true,
                            "read": true
                        }
                    }
                }
            },

            "mappings": [

            {

                "target_transformation": function(value) {
                    return localStorage.getItem('selectUser');
                },
                "target": "$['body']['user']"

            },

            {

                "target_transformation": function(value) {
                    return localStorage.getItem('thumbnail_id');

                },
                "target": "$['body']['thumbnail_id']"

            },

            {

                "target_transformation": function(value) {
                    return localStorage.getItem('selectPhotoName');

                },
                "target": "$['body']['photoName']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["viewingPage_viewer_selectPhoto_query_service_onbeforesend_mapping_0"] = {
        "homeScreen": "viewingPage",
        "directions": [

        {

            "to_name": "viewer_selectPhoto_query_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "Content-Type": "text/plain"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "target_transformation": function(value) {
                    var inW = window.innerWidth;

                    return inW;
                },
                "target": "$['parameters']['winW']"

            },

            {

                "target_transformation": function(value) {
                    var deviceOS = localStorage.getItem('deviceOS');
                    return deviceOS;
                },
                "target": "$['parameters']['deviceOS']"

            },

            {

                "target_transformation": function(value) {
                    var v1 = localStorage.getItem('hcjName'),
                        v2 = localStorage.getItem('hcjFirstname');

                    return v2 + ' ' + v1;
                },
                "target": "$['parameters']['user']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["viewingPage_viewer_selectPhoto_query_service_onsuccess_mapping_0"] = {
        "homeScreen": "viewingPage",
        "directions": []
    };

    Apperyio.mappings["viewingPage_viewer_selectPhoto_delete_service_onsuccess_mapping_0"] = {
        "homeScreen": "viewingPage",
        "directions": []
    };

    Apperyio.mappings["viewingPage_viewer_selectPhoto_delete_service_onbeforesend_mapping_0"] = {
        "homeScreen": "viewingPage",
        "directions": [

        {

            "to_name": "viewer_selectPhoto_delete_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "Content-Type": "text/plain"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "target_transformation": function(value) {
                    var v1 = localStorage.getItem('hcjName'),
                        v2 = localStorage.getItem('hcjFirstname');

                    return v2 + ' ' + v1;
                },
                "target": "$['parameters']['user']"

            },

            {

                "target_transformation": function(value) {
                    return localStorage.getItem('selectPhotoName');

                },
                "target": "$['parameters']['photoName']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["viewingPage_viewer_mosaicView_query_service_onsuccess_mapping_0"] = {
        "homeScreen": "viewingPage",
        "directions": []
    };

    Apperyio.mappings["viewingPage_viewer_mosaicView_query_service_onbeforesend_mapping_0"] = {
        "homeScreen": "viewingPage",
        "directions": [

        {

            "to_name": "viewer_mosaicView_query_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "Content-Type": "text/plain"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "target_transformation": function(value) {
                    var deviceOS = localStorage.getItem('deviceOS');
                    return deviceOS;
                },
                "target": "$['parameters']['deviceOS']"

            },

            {

                "target_transformation": function(value) {
                    var inW = window.innerWidth;

                    return inW;
                },
                "target": "$['parameters']['winW']"

            },

            {

                "target_transformation": function(value) {
                    var v1 = localStorage.getItem('hcjName'),
                        v2 = localStorage.getItem('hcjFirstname');

                    return v2 + ' ' + v1;
                },
                "target": "$['parameters']['user']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["viewingPage_viewer_mosaicCaption_query_service_onsuccess_mapping_0"] = {
        "homeScreen": "viewingPage",
        "directions": []
    };

    Apperyio.mappings["viewingPage_viewer_mosaicCaption_query_service_onbeforesend_mapping_0"] = {
        "homeScreen": "viewingPage",
        "directions": [

        {
            "from_name": "photoFilename",
            "from_type": "LOCAL_STORAGE",

            "to_name": "viewer_mosaicCaption_query_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target_transformation": function(value) {
                    if (value) {

                        return '{"photoName":"' + value + '"}';

                    }
                },
                "target": "$['parameters']['where']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["viewingPage_viewingPage_VersionCheck2reload_service_onsuccess_mapping_0"] = {
        "homeScreen": "viewingPage",
        "directions": []
    };

    Apperyio.mappings["viewingPage_viewingPage_VersionCheck2reload_service_onbeforesend_mapping_0"] = {
        "homeScreen": "viewingPage",
        "directions": [

        {

            "to_name": "viewingPage_VersionCheck2reload_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "Content-Type": "text/plain"
                },
                "parameters": {},
                "body": null
            },

            "mappings": []
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.viewer_photoQuery_service = Apperyio.datasources.viewer_photoQuery_service = new Apperyio.DataSource(HCJphotoList_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["viewingPage_viewer_photoQuery_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["viewingPage_viewer_photoQuery_service_onsuccess_mapping_0"]);
            // console.log('data = '+JSON.stringify(data));
            formatData2str(data);;
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.viewer_photoLike_service = Apperyio.datasources.viewer_photoLike_service = new Apperyio.DataSource(HCJphotoLike_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["viewingPage_viewer_photoLike_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["viewingPage_viewer_photoLike_service_onsuccess_mapping_0"]);
            likeNumResponse(data);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.viewer_top10Likes_service = Apperyio.datasources.viewer_top10Likes_service = new Apperyio.DataSource(HCJtop10likes_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["viewingPage_viewer_top10Likes_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["viewingPage_viewer_top10Likes_service_onsuccess_mapping_0"]);

            formatData2str(data);;
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.viewer_selectPhoto_create_service = Apperyio.datasources.viewer_selectPhoto_create_service = new Apperyio.DataSource(HCJquizDB_userSelection_create_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["viewingPage_viewer_selectPhoto_create_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["viewingPage_viewer_selectPhoto_create_service_onsuccess_mapping_0"]);
            var v = localStorage.getItem('selectPhotoName');
            console.log('v = ' + v);

            document.getElementById('selx' + v).classList.remove("selectButton");
            document.getElementById('selx' + v).classList.add("buttonSelected");

            updateHTMLstr(v, 'buttonSelected');

            // alert('Image successfully selected.');
            ;
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.viewer_selectPhoto_query_service = Apperyio.datasources.viewer_selectPhoto_query_service = new Apperyio.DataSource(hcjSelectedPhotosQuery_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["viewingPage_viewer_selectPhoto_query_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["viewingPage_viewer_selectPhoto_query_service_onsuccess_mapping_0"]);

            formatData2str(data);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.viewer_selectPhoto_delete_service = Apperyio.datasources.viewer_selectPhoto_delete_service = new Apperyio.DataSource(hcjUserSelectionDelete_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["viewingPage_viewer_selectPhoto_delete_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["viewingPage_viewer_selectPhoto_delete_service_onsuccess_mapping_0"]);
            var v = localStorage.getItem('selectPhotoName');
            console.log('v = ' + v);

            document.getElementById('selx' + v).classList.remove("buttonSelected");
            document.getElementById('selx' + v).classList.add("selectButton");

            updateHTMLstr(v, 'selectButton');;
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.viewer_mosaicView_query_service = Apperyio.datasources.viewer_mosaicView_query_service = new Apperyio.DataSource(hcjMosaicView_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["viewingPage_viewer_mosaicView_query_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["viewingPage_viewer_mosaicView_query_service_onsuccess_mapping_0"]);
            formatData2mosaicView(data);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.viewer_mosaicCaption_query_service = Apperyio.datasources.viewer_mosaicCaption_query_service = new Apperyio.DataSource(HCJquizDB_photoInfos_query_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["viewingPage_viewer_mosaicCaption_query_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["viewingPage_viewer_mosaicCaption_query_service_onsuccess_mapping_0"]);
            format2mosaicCaption(data);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.viewingPage_VersionCheck2reload_service = Apperyio.datasources.viewingPage_VersionCheck2reload_service = new Apperyio.DataSource(hcjUpdateReloadCheck_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["viewingPage_viewingPage_VersionCheck2reload_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["viewingPage_viewingPage_VersionCheck2reload_service_onsuccess_mapping_0"]);
            console.log('data = ' + data.newVersion)

            var v = localStorage.getItem('viewingPageVersionNum');

            if (v != data.newVersion) {

                alert("A new update was pushed, your page will reload. Please wait.");
                localStorage.setItem('viewingPageVersionNum', data.newVersion);

                location.reload();

            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'viewingPage';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var viewingPage_onLoad = function() {
            viewingPage_elementsExtraJS();

            // pastBetaVersionMark("viewingPage");
            viewer_photoQuery_service.execute({});

            ;

            viewingPage_deviceEvents();
            viewingPage_windowEvents();
            viewingPage_elementsEvents();
        };

    // screen window events


    function viewingPage_windowEvents() {

        $('#viewingPage').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function viewingPage_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function viewingPage_elementsExtraJS() {
        // screen (viewingPage) extra code

        /* loadPopup */
        $("#viewingPage_loadPopup").popup("option", "positionTo", "#photoViewer");

        /* mosaicViewPopup */
        $("#viewingPage_mosaicViewPopup").popup("option", "positionTo", "#viewingPage_mobileheader");

    };

    // screen elements handler


    function viewingPage_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#viewingPage_mobileheader [name="mobilebutton_11"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('uploadPage', {
                        reverse: false
                    });

                }
            },
        }, '#viewingPage_mobileheader [name="mobilebutton_11"]');
        $(document).off("click", '#viewingPage_mobileheader [name="mobilebutton_18"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    var popupElement = Apperyio("loadPopup");
                    if (popupElement.popup("option", "positionTo") === "origin") {
                        popupElement.popup("open", {
                            transition: "none",
                            positionTo: "#" + $(this).attr("id")
                        });
                    } else {
                        popupElement.popup("open", {
                            transition: "none"
                        });
                    };

                }
            },
        }, '#viewingPage_mobileheader [name="mobilebutton_18"]');

        $(document).off("click", '#viewingPage_loadPopup [name="mobilebutton_17"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        viewer_photoQuery_service.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#viewingPage_loadPopup [name="mobilebutton_17"]');

        $(document).off("click", '#viewingPage_loadPopup [name="mobilebutton_20"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        viewer_top10Likes_service.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#viewingPage_loadPopup [name="mobilebutton_20"]');

        $(document).off("click", '#viewingPage_loadPopup [name="mobilebutton_21"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        viewer_selectPhoto_query_service.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#viewingPage_loadPopup [name="mobilebutton_21"]');

        $(document).off("click", '#viewingPage_loadPopup [name="mobilebutton_51"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        viewer_mosaicView_query_service.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#viewingPage_loadPopup [name="mobilebutton_51"]');

        $(document).off("click", '#viewingPage_mosaicViewPopup [name="mobilebutton_60"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    $("#viewingPage_mosaicViewPopup").popup("close");

                }
            },
        }, '#viewingPage_mosaicViewPopup [name="mobilebutton_60"]');

    };

    $(document).off("pagebeforeshow", "#viewingPage").on("pagebeforeshow", "#viewingPage", function(event, ui) {
        Apperyio.CurrentScreen = "viewingPage";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    viewingPage_onLoad();
};

$(document).off("pagecreate", "#viewingPage").on("pagecreate", "#viewingPage", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    viewingPage_js();
});